# Generated by Django 5.0.7 on 2024-07-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_room_is_available"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="is_canceled",
            field=models.BooleanField(default=False),
        ),
    ]
