# Generated by Django 5.0.7 on 2024-07-30 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_remove_booking_is_canceled_alter_booking_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
